export { default as Logo } from './logo'
export { default as Cart } from './cart'
export { default as Star } from './star'
export { default as Heart } from './heart'
export { default as Car } from './bag'
export { default as Bag } from './car'
export { default as Check } from './check'
export { default as InActiveStar } from './inActiveStar'
